# Generated by Django 2.2 on 2019-05-25 16:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individual_votings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voting_id', models.IntegerField(unique=True)),
                ('voting', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Votings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('voting_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
