# Generated by Django 2.2 on 2019-06-01 09:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualVoting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('voting_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('genre', models.CharField(max_length=30)),
                ('topic', models.TextField(default='')),
                ('description', models.TextField()),
                ('votes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pre_name', models.CharField(max_length=30)),
                ('faction', models.CharField(max_length=60)),
                ('voting', models.ManyToManyField(related_name='politicians', through='dashboard.IndividualVoting', to='dashboard.Voting')),
            ],
        ),
        migrations.AddField(
            model_name='individualvoting',
            name='politician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Politician'),
        ),
        migrations.AddField(
            model_name='individualvoting',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Voting'),
        ),
    ]
