# Generated by Django 2.2 on 2019-05-20 19:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votings',
            fields=[
                ('voting_id', models.AutoField(primary_key=True, serialize=False)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='voting',
            name='votes',
        ),
        migrations.DeleteModel(
            name='Politician',
        ),
        migrations.DeleteModel(
            name='Voting',
        ),
    ]
