# Generated by Django 2.2 on 2019-05-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votings',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
