# Generated by Django 2.2.2 on 2019-08-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='individualvoting',
            unique_together={('politician', 'voting')},
        ),
    ]
