# Generated by Django 2.2 on 2019-05-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dashboard_individual_votings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard_individual_votings',
        ),
        migrations.DeleteModel(
            name='Individual_voting',
        ),
    ]
