# Generated by Django 2.2 on 2019-05-24 15:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190524_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual_votings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('voting_id', models.IntegerField(unique=True)),
                ('voting', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
