# Generated by Django 2.2 on 2019-05-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_individual_votings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual_votings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
